[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15.7"
shared = { path = "../shared" }
actix-web = "4.9.0"
actix-cors = "0.7.0"
serde = "1.0.216"
serde_derive = "=1.0.216"
