[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
serde_derive = "1.0.217"
structmap = "0.1.6"
structmap-derive = "0.1.6"

[lib]
crate-type = ["cdylib", "lib"]
